---
{{- with .Values.app.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
